# Generated by Django 4.2 on 2023-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('', 'Select a Priority'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('work in progress', 'Work In Progress'), ('completed', 'Completed')], default='new', max_length=100, null=True),
        ),
    ]
