# Generated by Django 4.2 on 2023-04-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='percentage_complition',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
