# Generated by Django 4.2 on 2023-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedsite',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
