# Generated by Django 4.2 on 2023-04-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
